---
volumes:
  mysql_data:
services:
  db:
    image: mysql:5.5.62
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'my_user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'a_stoopid_password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'another_stoopid_password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      # Where our data will be persisted
      - mysql_data:/var/lib/mysql
